import { ThemeProvider as NextThemesProvider } from "next-themes";
import { NextUIProvider } from "@nextui-org/react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Header } from "@/components/header";
import { Main } from "@/components/main";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="dark">
            <Header />
            <Main>{children}</Main>
          </NextThemesProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
